extensions:
  - timonwong.shellcheck
  - mads-hartmann.bash-ide-vscode
  - esbenp.prettier-vscode
  - dbaeumer.vscode-eslint
  - christian-kohler.npm-intellisense
  - eamodio.gitlens
  - knisterpeter.vscode-commitizen
  - mhutchie.git-graph
  - rogalmic.bash-debug
  -gruntfuggly.todo-tree
settings:
  editor.formatOnSave: true
  prettier.enable: true
  eslint.enable: true
  eslint.validate: ["javascript", "typescript"]
  shellcheck.enable: true
  shellcheck.useWorkspaceRootAsCwd: true
  gitlens.hovers.currentLine.over: "line"
  commitizen.path: "cz-conventional-changelog"
  debug.node.autoAttach: "on"
  tasks.runners: ["pnpm run parallel"]
launch:
  configurations:
    - name: Debug vscode.sh
      type: bashdb
      request: launch
      program: "/vscode.sh"
      cwd: ""
      terminalKind: integrated
      args: []
dependencies:
  - jq
  - git
validation_rules:
  version: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
  description_min_length: 10
  boolean_values: ["true", "false"]
  DOMAIN:
    type: string
    min_length: 3
    required: true
  HOST:
    type: string
    min_length: 4
    required: true
  PROJECT_NAME:
    type: string
    min_length: 5
    required: true
  VERSION:
    type: semver
    required: true
  REQUIREMENTS:
    type: boolean
    required: true
  GIT_ENABLED:
    type: boolean
    required: true
  SYNC_LEVEL:
    type: enum
    values: [patch, minor, major]
    required: true
  # Add more keys as needed (e.g., env_version: type: semver, required: true)