extensions:
  - timonwong.shellcheck
  - mads-hartmann.bash-ide-vscode
  - esbenp.prettier-vscode
  - dbaeumer.vscode-eslint
  - christian-kohler.npm-intellisense
  - eamodio.gitlens
  - knisterpeter.vscode-commitizen
  - mhutchie.git-graph
  - rogalmic.bash-debug
  - gruntfuggly.todo-tree
settings:
  editors.formatOnSave: true
  prettier.enable: true
  eslint.enable: true
  eslint.validate: ["javascript", "typescript"]
  shellcheck.enable: true
  shellcheck.useWorkspaceRootAsCwd: true
  gitlens.hovers.currentLine.over: "line"
  commitizen.path: "cz-conventional-changelog"
  debug.node.autoAttach: "on"
  tasks.runners: ["pnpm run parallel"]
launch:
  configurations:
    - name: Debug vscode.sh
      type: bashdb
      request: launch
      program: "/vscode.sh"
      cwd: ""
      terminalKind: integrated
      args: []
dependencies:
  - jq
  - git
validation_rules:
  DOMAIN:
    required: true
    type: string
    min_length: 3
    error_code: E001
    help_comment: "Project domain (e.g., 'davit')"
  HOST:
    required: true
    type: string
    min_length: 4
    error_code: E002
    help_comment: "Server hostname (e.g., 'node')"
  PROJECT_NAME:
    required: true
    type: string
    min_length: 5
    error_code: E003
    help_comment: "Project name (must match folder)"
  VERSION:
    required: true
    type: semver
    error_code: E004
    help_comment: "Semantic version (X.Y.Z)"
  REQUIREMENTS:
    required: false
    type: boolean
    error_code: E012
    help_comment: "Check requirements (true/false, optional default true)"
  GIT_ENABLED:
    required: false
    type: boolean
    error_code: E013
    help_comment: "Enable Git (true/false, optional default false)"
  SYNC_LEVEL:
    required: true
    type: enum
    values: ["patch", "minor", "major"]
    error_code: E007
    help_comment: "Sync level"
  # Add more keys as needed (e.g., env_version: type: semver, required: true)
